// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "myImage":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "image2":
            case "myImage0":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "u-$RaA|P^`/DE2ot9ZkB":
            case "galaxy":return img`
fccccfcfffffffffffffcfffccffcfcfffffffffffffffffffffffffcffffffffffffffffffffffffffffcfffffffffcffffffcfffffffffcffffffffffcffffcffffffffbfcffcfffccffffffffffc
cffcfffffffcffffffffccfffccfffffffffffffffffffcfffffffffffffffffffffffffffffffffcfffffffffffffffffffffcffffffcfffffffffffffcffffcfcfffffffffffcffffffcffffffffc
cfffcfffffcfccffffffffcfcfcffffcffcffffccffffffcffffffffcfffffffffffffffcffffffffffffffffffffffcffffffffffffffffcfffffffffffffffffcfffffcfcfffffffcffcfffffcfcf
ffffcccffffffffcfffffffffffffcffffffffffffcfffffffffffffffffffffffffffffffcfffffffcfffffffffffcfffffffffffcfffffcfffffffffcfffffffffffffffcfffffcffcfccfcffffff
cffcffccffffcffffffffffffffffffffffffcffffcffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccfcfffcffffffffffcfffffcfffffcfcfffffc
fffcfcfffffcfffffffffcfffcffffffffffffcffffffffffffffcffcfffffffffffffffffffffffffffcfffffffffffffffffcfffffffffffffffcffffffffffffffcfffffffffffcfcffffcccffff
fcfffffffffffffcffccfcfcfffffffffffffffffffffffffffcfffcfffffffffffffffffffffffffcffffffffffffffffffffffffffffffffffffffffffcffffffffcfffffffffcffcffffffffcffc
cfffccfffcfffffffccccfffcfcfffffffffffffffcffffffffcffffffffffffffffffffffffffffffffcfffffffffffffffffffffcffffffcffffffffffffffffcfcfffffffffffffffffffccffffc
fcfccffffffffffffccffccccfffcffcffffffffffffffffffffffcffffffffffffffffffffffffffffcfffcfffccfffffffffffffffffccffffffcffcffffffffcfffffffccffffffffcffcfffffcf
cfcfccffffcffffffffffcccffffffffffffffffffffcfffffffffcfffffffffffffffffffffffffffffffffffcfcfffffffffffffffcffffffffffffffcfffcfffffffffffcfffffffcffffcfffffc
ccfccfccfcfcfffcffcfcffccfffffccfffffffffffffffffffffffccfcfffcffffffffffffffffffffcffffcfffffffffffcffffffffffffffffffffffffffffffffffffffcfffffffffffffffffcc
ffcccfccfcccffccccccccffffffffffffcfcfffffffffffffccfffcfffffffffffffcfffffffffffffffffffcffffffffffffffffffffffcfffffffffffffffffffffffffcfffffcfffffffffffccf
fcffcfccfffcffccccfcfffcfcfffffcffffcffffffffffffffffffffffffffffffffffffffccfffffffffffffffffffffffcffffffcffffffffffffffcfffcffcfffffffffffffccfccfffcfcfcfff
fffccccfcfccfcccfcfcfffcffffffccffffcffffffffffffffffffcffffffcffffffffffffcffffffffffffffffffffffffffffffccffffffffffffffffffcffffffffffffffcfffffccffcffcffcc
fcfcfcfccffcccccccfccfffffffcfcfffffcffffcfffffffffffffcffffffcfffffffffffffcfffffffffffffffffffffffffffffcfffffffffffffffffffffffffffffffffcffffffffffcffffcfc
fcccfcccccfcccccccffcccfffcfcffcfffffccccffcfffffffffffcfffcfffffffffcffffffffffffffffffffffffffffcffcffffffffffffffffffffcfcfcffcffcfffffcffffcffcffcfcfffcfff
cccccccccccccccccccfcccfcfcffffffccfffffffcffffffffffffffffffffcffffffffffffffffffffffffffffffcfffccfffffcfcfffffffffffffffffcffffffffccfffffffffcfffccccffffcf
ffcccccccffccfccfccfcfcccccccccfcfcffffffffcffcfffffffcffcfcffcffffcffffffcffffffffffffffffffffffffffffffffcfffffffffccfffffffffcfffffccffffcfffffccfcfcfcfcffc
ccfcccccccfcccfccccccccfffffffccfcffffffffffffffcfcfcffffffcffffffffffffccffffffffffffffffffffffffffffffffcffffffcfffffffffffffffffffccccfffcfcffffcffcffcfffff
cccfccccfcfccccccfcfcffffcccccfccffcffffffffffffffcffcfffcfffffffcfffffffcfffffffffffffffffffffffffffffffffffffffcffffcffffcffffffcffcfffffcfffcfcfcffffffccfff
cccccccccccccfccccfccfcccfffffcfcffcfffffcfffcffffffccfffcfffffffcffffffffcffffffcffffffffffffffffffffffffffffffffffcfffffffffffffcfffffccfffffffcfffcffcfcfcff
cfcccccccccccccccccccfccccccccfccfcffcccfffffffcffffcffcffffffffffffffffffffffffffffffffffffffffffffffffcfffffffcccfffffffffffcfffffffffffcfffffffcffcfccccffff
ccfcfccfccfcfccccccccccccffffcfffccfcfffffffffffffcfccfffcffffcccffffffffffffffffffcfffffffffffffffffffcfffcfffffcfccffcffcfffffffcfffcfcccbfffccfffcffffffcccc
cccfccccccccccccccccccccfccccfccffffccfffffffffffffccffcfcfffcfffffffffffffffffffffffffffffffffffffffffffffffffffccfffffffffffffcffffccfffffccffcccfcfcffcfcfff
fcccccccccccccccccfcfccfffcfcccc8fffcccffcfcffcffffcffcffccfcfffffffffffffffffcffffffffffffffffcfcfffffffffffffffffffffffcfffffffcffffccfffffcfccccfcfffcccfcff
cccccccccccccccccfcccfccccccccfcccfffffffffcfffcffffcffffcffcccffffffccfffffffffffcffffffffffffffffffffcffffffffffffffffffffffcffffcfffffffcfcfcfcccfcfccfcfcff
ccccccccccccccccccccccccccfcccfcfcccffccffccffffffffcffffcfffffffffffcffffffffffcffffffffffffcffffffcffcfffffffffffffffffffcffcfffffffcffffcccfcccccffcffffffff
cccccccccccccccccccccccccccccccccccffffccfffffcfffccfcccfffcffffccfcfffcffffffffffcffffffffffffffffffffffffffffcfffffffffffcfcfffffffffffffffffffccfcffcfcfcfcf
cccccccccccccccccccccccccccccccccfccccfcccfcfcccffccffffccfffffffffffffcffffffffffffffffffffffcfffffffffcffccfffcfffffffcfffccfffccffcfcccfffcccfcccffffccfffff
cccbccccccccccccccccccccccccccccccffcffccccccccffffffffffffffcffffffcffffffffffffccffcffffffcfcffcffffffffccccffcfffffcfcfffffffffcfcffffcfffffcfffccffffcccccf
cccccccccccccccccccccccccccccccccccccccccccfffcffcfffffffccfffffffcfffffccfcfffffffffffffffffffffffffffcfccfcfffffffcfffffcfffffcffffffffcfcfcfccffffcfffcccfff
ccccccccccccccccc6ccccccccccccccfccccccfcccfccfffcfccffcffcfcffffffcffffffcfffffcfcfffcfcfffffffffcfffffffffffcffffffcfffcffccffffcffffffffccfffccfcccffcfccfff
cccccccccccccccccccccccc8ccccccccccfcccfccfffcfcccccffffccfcfffffccfffffffffffffffffffffcfffcfffffffffffcfcffffffccffffffcfffcffccffffcfffcfffccccfccccffcccfcc
cccccccccccccccccccccccccccccccccccfccccccffcfcfccfccffcfcfcfcffffffcfffffffffffffcffcfffffffffffffffffffffccfffffffffffffffffffcfffffffccffcfccffcccffcccfffff
ccccccccccccccccccccccccccccccccccccccccccccffcffcccfcccfcccffffcfffffffffffffffcffcffcffcfffffcffffcffcfffffffffcffffcfccfffffffccffcffffffffcccccccccccfffcfc
cccccc6ccccccccccccccccccccccccccccccccfccccccfcffcffccffffffffffcfcfffffffcffcfffffffcfccfffcfffcbfcfffcfffffffffccfffcffccccfccfcfcffffffcffccccffcccffcffffc
cc6ccccccccccccc6cccccccccccccccccccccccccccccccfcffcccfcccffffffffffffffcfffffffcfffffffcfffffffccfffcfcfffffcfcfcfcffffffffffcffffffccffcfffcfccfffcccccccfff
cc6cccc6cccccc6cccccccccccccccccccccfccccfccccccccccffffffccfffffccccffffffcffcffcfffffcfccffffffffcfffcfffffffffffcccfffffccfffffcfccfcffcffffccfccffcccfcffff
bcc6c6ccccccccccccccc6cccccccccccccccccccccccccccfcfccccccccffccfffffffffffffffffcffccfffffcffffcfffffffffffcfcfccffffcfcfcfffcccfcfffcfcffcccccccccfccccfccfcf
ccbc66ccccc6c6ccccccccccccccccccccccccccccccccccccccccccccfccfcffffcffcffffffffffffcfffffffcffffccffffffffcfffcffcfccfcffccfffcfcffffffccfffcfcfccccccccccccfff
cccbcccbcc6ccccbcccccccccccccccccccccccccccccccccccfcccfccccccfcffcfffffffcfffcffcffcfffcffffffcfffcccfffcccffccfffffffffcffccfcffffcfffccfcfcccccffccfccccccfc
ccccc6b6cccccccbccc6ccccccccccccccccccccccccccccccccccccccccccccfccfcffffffffcfffffffffffffffffcccffffcfcccfcffffffcfffcffffffffccccfffccfcfcccffccfccccccccfcc
cccccbbbcccccccccb6c6ccbccccccccfcfccccccffcccccfccccccccfcffccffcccfffccfcffffffccffffcffffffccffcfffffcfffffcfccfccccfcfffffffcfccffcccfcfffcffcffccccffccccc
cccccbbcccccbbbcbcbccccccccccccccccfcccccccccccfcccccfcccccccccccffcfcffcffcffffffcfcfcfcfcfcccfffcffccffcfccffccffcffffcffffffcffccfcfcccfccfccfcccccccccccccc
ccccccbcbbcbbbcbbccbc6ccccccccccccccccccccccccccfcccccccccccccccccccfcfffffffffcfcfcffffccccfcffffccfcccfffffcfffcfffcffffccfffffcccfffcfcfcfccfccccccfcccccccc
ccccbbcccbbbbbbbbcbcccccccccccccccccccccccccccccccccccccccccccccccccfcffcffcccffcccfcffcffffccccfffcfcffcccfcfccffffcccffffffcfcccffcffcfccccccfcffcccccccccccc
ccccbbcccbbbbbbbbccbccbcccccccccccccccccccccccccccccccccccccccccffcfcffccfcffffffffccfccccccffcfffccccffccccfccfcfcfcccfffcfcfcfccffcccfccccccccccccccccccccccc
bcccbdbccbbbbbbcccbbcbccbccccccccccccccccfccccfcfcccfccccccfccccccccccfcccccfccccfcfccfffccccccffccccccccffccccffffffcfccfffffccffcccfccccfcccccccccccccccccccc
cccccccccccbbbcccccccbcbcccccccccccccccccccccccccfccbcccccccccccccfcccccfffcffcfccccfcccccccccccffccccccccfccccccfcffffffcfffcccccccfcccfcfcccccccccccccccccccc
ccccccccccccbccccccbcccbbccccccccffcfcccccccccfccffccccccccccccccccffccccfcfcccccccccccccccccccccccccffccccffccccfccccccfcffcccfffccccccffffccccccccccccccccccc
ccccbcccccccccccccccbbbcbcccccccccffccccfcfcccccfcccccccccccccccccccccccccccccccccccfccccccccccccfcccccfcccccfcccfcfcffcffffccfccccfccccccfffccfcfccccccccccccc
ccccccccccbccccccccccbccccccccccccfcccffcccccccccccccccccccccffcfccccccccccccccccccccccccccccccfcccccccccccccccccfccccfccccfcccfcfcccccccffcccffccccccccccccccc
cccccccccfccfccccfbccccccccccccccccccffccccccccfccfccccccccccfffffccfcccccfffccccccccccccccccccccccccfcccbcccfcccccfcfccfffffccccccfcccffcccfcfcfcccccccccccccc
ccccccccccfcccccfcccccccccccccccccccccfcccccfcccccccccccfcccccfffccccfccccfffccccccccccccccccccccccccccccccfcccccccccccfcccffcccccccccccccfcccccfcfcccccccccccc
ccccccccccccccccccccccccccccccccccccccccccccccffcccccccccccffcffcccccccccccfcccccccccccccccccccfccccccccccfccfccccfcccccccccfccccfcccccccffccccccfccccccbbccccc
ccccccccccccccccccfccccccfccccfcfcccccccccccccfccfccffcccfcffccfccccccccccccfccccccccccccccccfccccfcfccfccccfccffcccccccccccffcccccccccccfccccffccccccbccbccccc
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfcffcffcccccccccccccccccccccccccccccccccfcfcccccfccccccccfcccccfcfcccccfcfcccccfccccfcfcccccbbccccccc
cccbccccccccccccccfccccffcfccccccccccccccccccccffccfcfffffcfffcccfccccffccccccfccccccccccccfccccfcccffccfcccffffccfcffccccccfcfcccccccccfffcffcfcfcccccbccccccc
cccccccbccccccccfccccccccccccccccccccccbcccccccccccccccfcccfccfccccccccfcccccccfcccccccccccfcccccfcfffcccfcfccccfccfccfcffcccccccccccccccccccffcfcccccccccccccc
ccccbcccbcccbcccfcfccccfffccccfcfcccbcccccbcccccccccfcccfffccfffccccccccfccccccccccccccccfcccccccfffffffcccccffccccccccffcccccccccccccccccfcfcccccccccccccccccc
ccccbccccbcccccccfccccccfcccccccccbbbcbccccccccccccccccccfffffcccccccccfcccccccccccccccccccccccccffffcffffccccccccccccccccccccccccccdccccfcffccfcfccccccccccccc
ccccbbcccbbcccccccccccccccccccccccbcccccccccccccccccccccfcffffcfccccccccfffffccccccccccccccfcccccccfcffccfcccccccccccccccccccccccccccccfcfbfcccccfcccfccccccccc
cbccccbccbccccccccfcfcccccccccccbccbbccbccbcccccccccccccccfccffcfcccfcfcfccfcccccfccfccfcfcccccccccccccffcccccccffccfcfcffcffcccccccccccccffffffccfcfcccccccccc
cccbccccccccccccccccfcccccccccccccbbbccccccccccbbcccccccccffffcccccccccfffcffcccfccfcccccccccfcccccccccffcccfcccccffcccfcfccccccccccccccccfffffcfcccccccccccccc
cbcbcccccbbccbccfcccfccccccbccccccccbccccccccccccccccccccccfffccccccfffffffffcfcccfffffcffcfffffcccfccccccccfcccfffcffccffccccccccccccccccfffcccfcccccccccccccc
cbbcbccbccccccccccfcccccccccccccbbbbbbccbccccccccccccccfccfffccccccffffffffffcffccfcffccccfffffcffcffccccccccccccfcffcffccccccccfcccfccccffccccfcfffcccccccbccc
cbbcc66ccbcccccccccccccccccccccccbbbbbccbccccccbcccccccccccffccccccfcffffffffffffcffccccffffffffffcfccffcccccccccffcfccffccccccfcfcfcfcccffccccfcfccccccccccccc
cbc6c66cccccccccccccccccccccccccccbbcccccbccccccccccccfccfffcffccccfcfcfffffffffccffffcfcfffffffffffcffffccccccfffcfcffffffcccccccfcfcfccccfcffcccfccfccccccccc
cccc666cccccccccccccccccccccccccccccbbccccccccccccccccccccfcccccccfccfcfffffcffffffffffccffffffffffccffffccfcffffcfcfcffccccfffffffccffffccfcfcfcfccccccccccccc
cc6b6866ccccccccccccccccccccccccccccccccccccccccbcccccccccfccccccffcffffffffffcfffccfffccccffcfffcccffffcfffcfffffccfccffcfcffcffcfcccccfcffcffffccccfccccccccc
cc6866ccccccccccccccccccccccccccccccccccccccccccccccccccfccccccccccfccffffffffffffcfcfffcfffffffcfccccfffcffcfffffcffcfcffcccfccffccccccccfcfcfffffcccccccccccc
c6886cc6ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccffcfffffffffffffffcfcfcccfcffffffccffffffffffffcffffffcfcfffccccffccfcccfccccfffccccccccccccc
c688cccc6c666cccccccccccccccccccccccccccccccccccccccccccccccccffccfffcffffffffffccccfffffcfcfffcffffffccfffcfcfffccfcfcfcccccccffcffcfffcffcfccfcfcfccccccccccc
6c88ccccc6cccccccccccccccccccccccccccccccccccccccccccccccccccccffffccfffffffffffffffffffccffccfffffffffffffcffffcffcffffffffccfccfcccfccffcbccccfcccccccccccccc
c88ccccccccccccccccccccccccccccccccccccccccccccccccccccccccfccfcfffcccffffffffffcfffffccccccffcffcffcfffffffcfffffffffffcfffffcfffccfccfcfcccfcccccbccccccccccc
88ccccccccccccccccfccccccccccccccccccccccccccccccccccccccccccffcfccffccfffffffffffcffffcccccffffcffffffffffffffffcfcffffffffffffcfcfcfcfcccfcbcccfccccccccccccc
8c8cccccccc6ccccc88ccccccccccccccccccccccccccccccccccccccccfccfcfccfccfffffccfffffffffccccfcffcfffcfffffffffffffffffffffffffffffffffffcccffcccccccfcccccfcccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccfffcfcffcccccccfccfffcffffffffcccfcfcffffffffcfffffffffffffffffcfccfffccffffcfcffffccfcccccfccccccffcccc
cccccccccccccccccccccccccccccccccccccccccccccfcccccfcccfccccccfffccccccfffcffffffcfffffffffcffffffffffffffffffffffcccfffffcffffffcffccccccffccccfcccccccccccccf
cc8cccccccccccccccccccccccccccccccccfccccfccfccccccccccfcccffffcfccfccfffffcfffcfffffffffffcfffffffffffffffffffffffcfffcfffffcffffcfffcfffcccccfccfccccccccfccc
88ccccccccccccccccccccccccccccccccccccccccccccccccfcfccfcccfffccccffcfcfffffffffffffcfffcffccfffffffffffffcfffffffcfcfffcfcffffcfffcfffcfffccfccccccccccccccccc
888cccccccccccccccccccccccccccccccccfcccccfccccfccccfccccfcccfcfcfffffffccfffffffffffffffffcffffffffffffcffffffffcfcffcffffffffcfffffccfffccfcccccccccccccccffc
ccccccccccccc6ccccbcccccccffcccfcfccccccfcccffccccccccccfcccfffffccfffcfffcfcffffffcffcfffcfffffffffffffcfffffffccfcffccffcffcffffffffffbffccccfbccfcccccccccff
cccccccccccccccccccccccfcccccccccccccccfccccccccfcfccfcccfccfccccccffccffffffffffffcffccfffcffffffffffccfcffffffffffcfffffffffffcfffffccfccfccccfcccccccccccccc
cccccccccccccccccccccccccccffccccccccccfcffcfccffccfffccccffcfffccffcfccffffffffcfffffffffffcfffffcffffffcffcfffffffcffffccfffcffffffcfffccfccccfcccccccccccccc
cccccccccccccccccccccccccccfcccfccccccfcccccccccccfcfccfffcfcfffcffcffffffffcfffcffffffffcfffffffccffffffcfffffffcffcfffccffffffcffcffffcfcfcccccffcccccccccccc
c8c8cccccccccccccccccccfccccccccccffccfccccfccccccfffcccffcfcfffcffffcffffffcffffffffffffffffffccfffffffffffffcfffffcfccffcffcfcfffffcffffffccccccfcccccccccccc
fcccccccccccccccc8c8fccccfcccfcffcccffccffcfcffffffcffffccccffffcccffffffffffffcfccffffffffffffffffffccfffffcfffffcffccffffffcfffcffffffffccfccccccccccccccfccc
8ccccccccccccccccccccccccccfcccccccfccccccffcfccfffffffffcfcfcfcffffffffffcffffcffffffffffffccffffcfffcffffffffffcfffffffcffccffffffffcfffcffcccfcccffccccccccf
8cccccccccc8ccccccccfccccffcfcfccccfcccfccccfcfffffffcfcfcfcfffffffffffffcfcfffffffffffffffffffffcffffffccffffffffcfffffffffffffffffffffffffffcffcccffccccffcff
88ccc8cccccccccccc8ccccffccccccccccfcccffcccffffcffcfcffffcfffcfffffffcfffffffffffffffffffffcfcffcffcffffffffffffffffcffcffffcffffcfffffcffffcfcfccfccfcccccfff
cccccccccc8ccccccc8cccfcccfccccffccfcfffffccfcfcfffffcffffccccfffcccfffcffffffffffffcfffffffcffcffcfffffcfffffffffffffcfcfcfffffffffffffcffffffcffcccccfcccfcff
ccfccccccccc6fcc8ccccccccccccccccfccfcffcfcfffcfccfccfffcfcfffffcfffccffccfccffffffffffffffffffcfcffffffccffcffffffffffffffcffffffffffccfcffcfffffffccccfcffcff
ccccccccccccccccccccccffcfcccccccccfcffcfcfcccfcffffcfcffcfcfffffffcffffffcfffffffffffffffffffffffffffffffffffffcffcfffffffffcfffcffffcfcfffcfcffcccfccfffcccff
ccccccccc8ccccccccccccccccccccfccfffccccffcfccfcffcfffffcfcfffffffcfffffffffffcfffffffffcffffffffffffffffcffffffffffffcffffffffffcfffffcffffffcccccccfcffffccff
ccccccccc88cccccccccccccccfcffffccccfffccffffffccffccffcfffffcffcfffffffffcffcffffffffffffffffffffcffcffcfcccffffffffffcfffffffffcffcfcfcffcfcfccffffcccfffccff
fcccccccccccccccccccfcccccfcfccccccffccfcffcffccfffcffffcffffffffffffffffffffffcfffffffffffffffffffffffffffffffffffffffffffffccffffccfffffcffcffffcfcccffcfccff
ccccccccccccccccffcfcccccccccccccffcccccffffcfcfffffcfcfffccfffcffcffffcffffffffffcffcfffffffffffffffffcffcfffffffffffcfffffcfcfcfcfffccfffcffffcffcfccccffffff
ccccc8cccccccf8cccfcfcccccffccfffcffcfccccffffcfffffffffffffcffffffcffffffffffffffffffffffffffffffffffffffffffffffcffcfffffffffffffcfcfffcffffcfccfccfcfcffffff
ffcccccc88ccc8ccccccfcfccfcfffcfffffcfccfccfccfffcfffffffffffffcfcfffffffffffffffffcfffffffffffffffffffccffffcfffcfcffffffcfffffffcfffcfffcffcffcffffccccffcfff
fffff8cf8ccccccccffccccffccfccfccccfffcfcfcffffffcffffffcffffffffffffffffffffffffffffffffffffffffcffffffffcffffffcfffffffffffffcfcffcffffcccfcfffcfffccfccfcfff
fcfccccccccccfccfccfcccccfffccfccfffffffccfffffffffcfffffffffffcfffffffffffffffffffffffffffffffcfffffffffcfffffffffffcffffffffcfcfcfcfffcfcfcfccfcccffffccfcfcc
cfccfccccccf8cfcfccfccfccccccccffffcffcffffffcffffffffcffffcfffffffffffffffffffffffffffffffffcffffffffffffcfcffffccfffcfffcfffcffffcfccfffcfcccffccccccfcffcccf
cfcfccfcfcfccfffcfccccccfcccfffcfcfffccffffffcffcfffffffffffffffffcffffffffffffffffffffffffffffffffffffffffffffffffcfffffcffffffcfffffcffcffcffcffffffccfffccfc
ffcccfffccffcccffcccfccccffcccfcfffcfccfcffcfcffcfcffffffffffffffcfffffffffffcfffffffffffffffffffffffffffffcffffcfffffffffcffccffcfcffffffcfcffcfcfcfcfffccccfc
ffccccccccccccccccfccccfcccffcfffccfffffffffffffcffffffffcfffcfffffffffffffffffffffcfffffffffffffffffffffffffcffffffffffcffcfffcfffcfffccffcfffffccfffffffcffcc
fffccccfcfcfcccccfffcffcfccfccccfffffcfccfffffffcfffffffccffffffffffffffffffffffcfffffffffffffffffffffffffcffffffffffffffffffffcfffffffffcccfcccfcfffccfcfffccc
cccfccffccccccccffffcccccccfcfccfcffcccffffffffffffcffffccfffffffcfffffffffffffffffffffffffffffccfffffffcfffffffffffffcffffccfffcffffcffccfcffffcfffcffcfffcfcc
ffccccfccfffffffffccffcccffcffcfccccfcffcffcffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffccfcffffcfffcffcfccfffcffffffffffcccc
fcfcfffcccccfffcfffffccfcfcccfcccffccfffffffffffffcfcffffffffffffffffffffffffffffffffffffffffffffcccffffffccffcffcfcfffffcffffffcccfccffcccfcfffffffcffffffcccc
cffcfffcccccffffffffffffcccffffccfcffffffffffcfffcccfffcfffffffffffffffffffffffffffffffffffffffffffffcfffffffffffffffffffcffffffffffcfcffffccffcffcccffffccfcff
fffccfffffffcfffccfffccfcfcccffccfffffcfcfccffffffccffffffffffffffffffffffffffffffffffffffffcffffffffffffffffffcfffffcffffffffffffcffffffffcfffcfcfffffffccffff
fccfffcfffffcfffffffcffccffffffcffffffcfcfcfffccffcffffffffffffffffffffffffcffffffffffffcffffffffffffffffffcfcfcfffcffffffcffffffccffcffcfffcfffffccfffffccfcff
cfffcfffffffffffffffccccfcffccfcfccfffffffcffffffffffffcffffffffffffffffffffffffffffffffcffffffffffffffffffffffffffcffcfffffffffffffcfffccfcfffffcfffcfffffccff
ffffffcffffcffffffffcfcffffffcccfffcfffcffcffcfffcfffcffffcfffffffffffffffccfffffffffcfffffffffffcfffffcfffffffffffffffffffffcccffffccffccfccccffccffffffcfffff
fccfffffffffffffffffffffffffffcfcffcccfffcfcccffffffcffffffffffffffffffffffffffffffffcfffffffffffffffffffffffffffffffffcffcfffccffffccffcffcffcffffffffffffffcc
fcfffffcffcffffffffffffffffffcfcfffffcfffcfcfffffffffffffffffffffffffffffcffffffffffffffffffcffffffffffffffffffffffffffffffffffffcffffffffcfffccffccfffffffffff
fcfffffcffffffffffffcfffffcffccffffcffffffffcffcffffffcfffffffffffffffffffffffffffffffffffffffffffffffffffffffcffffcffcffffffffffcfffffcfffffcfcffffccffffffcff
cfcccffffffffffffffffffcfffffffffcffcffffffffffffcffffffffffffffffffffffffffffffffffffffffffffffffffcfffffffffcfffffffffffffcffffffcfcfccffffcfcfcfffffffffcfff
ffccfffffffffffffffffffcffffffffffffffffffffffffcffffcffffffccfffffffffffffffffffffffffffffffffffffffffffcffcfffffffffffffffffcfcffcfcffcfcfcffcfcfffffffffcfff
`;
            case "image3":
            case "spaceship":return img`
...............................................................................................................................................................
...............................................................................................................................................................
...............................................................................................................................................................
...............................................................................................................................................................
...............................................................................................................................................................
...............................................................................................................................................................
...............................................................................................................................................................
...............................................................................................................................................................
...............................................................................................................................................................
...............................................................................................................................................................
...............................................................................................................................................................
...............................................................................................................................................................
...............................................................................................................................................................
...............................................................................................................................................................
...............................................................................................................................................................
...............................................................................................................................................................
...............................................................................................................................................................
...............................................................................................................................................................
...............................................................................................................................................................
...............................................................................................................................................................
...............................................................................................................................................................
...............................................................................................................................................................
...............................................................................................................................................................
...............................................................................................................................................................
...............................................................................................................................................................
...............................................................................................................................................................
...............................................................................................................................................................
............................................................................bccccb.............................................................................
...............................................................................................................................................................
...............................................................................................................................................................
.........................................................................bc.bddddbccb..........................................................................
.........................................................................b..c111dbffb..........................................................................
.......................................................................ccbbbbbbbbbbbbcc........................................................................
..........................................................................d1bffffb1dc..........................................................................
..........................................................................d1bffffb1dc..........................................................................
....................................................................bccbddcccbbbbcccddbccb.....................................................................
....................................................................bffc1dcfcbbbbcfcd1bffb.....................................................................
..................................................................cccbbb1dcfcb696cfcddbbbbcc...................................................................
.....................................................................d1dddcfcbb69cffddd1dc.....................................................................
.....................................................................dddddcfcbbbbcffddd1dc.....................................................................
...............................................................bcccbbdddddcfc1111bffdddddbbcccb................................................................
...............................................................bffcbbdddddcfc1111bffdddddbbcffb................................................................
...............................................................bffcbbdddddcfcddddcfcdddddbbcffb................................................................
...............................................................bffcbbdddddcfcbbbbcffdddddbbcffb................................................................
...............................................................bffcbbdddddcfcbbbbcfcdddddbbcffb................................................................
...............................................................bffcbbdddddddbffffcdddddddbbcffb................................................................
...............................................................bffcbbdddddddcffffcdddddddbbcffb................................................................
...............................................................bffcbbdddddddbccccbdddddddbbcffb................................................................
...............................................................bffcbbddddddddddddddddddddbbcffb................................................................
...............................................................bffcbbddddddddddddddddddddbbcffb................................................................
...............................................................bffcbbddddddddddddddddddddbbcffb................................................................
...............................................................bffcbbddddddddddddddddddddbbcffb................................................................
...............................................................bcfcbbdddddddbbbbbbdddddddbbcffb................................................................
...............................................................bcfcbbdddddddbffffcdddddddbbcffb................................................................
........................................................bbcb...bcfcbbdddddddcffffcdddddddbbcffb...1ccc.........................................................
........................................................c.cd...bcfcbbdddddccccccccccdddddbbcffb...dc.c.........................................................
...........................................................d...bcfcbbdddddcfc6c66cffdddddbbcffb...d............................................................
...........................................................d.bdbcfcbbdddddcfcccc6cffdddddbbcffb11.d............................................................
...........................................................d.d1bcfcbbdddddcfccccccffdddddbbcffb1d.d............................................................
...........................................................d.bbbcfcbbdddddcfcc6cccffdddddbbcfcbbb.d............................................................
...........................................................d.cccddbfcdddddcfc6ccccffdddddcfbddc...d............................................................
...........................................................d....ddbffdddddcfc6cc6cffdddddffb1dc...d............................................................
...........................................................d....d1bccbbbddcfcb777cffddbbbccb1dc...d............................................................
...........................................................d....d1dbbffcddcfcdbdbcffddcffbbd1dc...d............................................................
...........................................................bbc.cd1dbbffcddcfcbbbdcffddcffbbdddc.cbb............................................................
.............................................................bdddddbbffcddcfc7776cffddcffbbbddddb..............................................................
.............................................................c1dddbbbffcddcfc7cc6cffddcffbbbddd1b..............................................................
.............................................................c1dddbbbffcbbccccc77cccbbcffbbbddd1b..............................................................
.............................................................c1dddbbbfffffcc7cc77cccfffffbbbddd1b..............................................................
.............................................................c1dddbbbfffffccccccccccfffffbbbddd1b..............................................................
...........................................................dddddddbbbfffcc6cccccccccccfffbbbddddddd............................................................
...........................................................d1dddddbbbfff6667ccccc6666cfffbbbddddd1d............................................................
.....................................................c...ccdddddddbbbffccc77777777bbcccffbbbdddddddbcc..c......................................................
.....................................................c..c11dddddddbbbffcbbbddbdddddbbbcffbbbdddddddd1c..c......................................................
.....................................................c..c11dddddddbbbffcbbbddddddddbbbcffbbbdddddddd1b..b......................................................
.....................................................bc.c1ddddddddbbbffcbbbddddddddbbbcffbbbddddddd11b..b......................................................
.....................................................bc.c11dddddddbbbffcbbbddddddddbbbcffbbbdddddddddc.cb......................................................
......................................................bcbdddddddddbbbffccc77bb7bb777cccffbbbdddddddddbcbc......................................................
......................................................d1dddddddddddbbfffccccccccccccccfffbbbdddddddddd1d.......................................................
.................................................bbc.cddddddddddddbbccffcccc777ccccccccffcbbddddddddddddc.cbbb.................................................
................................................bcfbddddddddddddddb..cbcffcc677cccccffcbcc.bddddddddddddddbfcc.................................................
................................................ccfb1dddddddddddddb..bbcffc66c7cccccffcbb..bddddddddddddd1bfcb.................................................
.................................................bbbddddddddddddbcc..bbccccccccccccccccbb..ccbddddddddddddbbb..................................................
..............................................c..d1dddddddddddddc....bbbdb..c7cccc..bdbbb.....ddddddddddddd1d..................................................
............................................dbcccdddddddddddddddc....bbbdb..cccc6c..bdbbb....cbddddddddddddddcccbdb............................................
...........................................cc.cddddddddddddddbcccbc..bbbdb..cccc6c..bdbbb..cbcccbddddddddddddddb.cc............................................
...........................................cc.c11ddddddddddddbffcbc..bbbdb..cccc6c..bdbbb..cbbffcdddddddddddd11b..c............................................
.........................................c....cddddddddddddbccccbbc..bbbdb..cccccc..bdbbb..cbbccccbddddddddddddb....c..........................................
.........................................c....cddddddddddddcfcddbbc..bbbbb..cccc6c..bbbbb..cbbddcffddddddddddddc....c..........................................
.......................................dbe....cddddddddddddcfcddbbc..cbbbb..c7777c..bbbbc..cbbddbfcbdddddddddddc....cbd........................................
.......................................c..cc..cdddddddddbfcbddddbbc.........cbbbbc.........cbbddddbcfbdddddddddc..cccfcc.......................................
.......................................c..cc..cdddddddddbffdddddbbc.........cbbbbc.........cbbdddddffbdddddddddc..ccfffc.......................................
.......................................c..6c..cdddddddbccffdddddbbc..ccccc..cb7b7c..ccccc..cbbdddddffccbdddddddc..c6fffc.......................................
..........................................6c..cdddddddcffffdddddbbc..bbbbb..cc6c6c..bdbbb..cbbdddddfffffdddddddc..c6fffc.......................................
.......................................c..6c..cdddddddccfffdddddbbc..bbbdb..c6cc6c..bbbbb..cbbdddddffffcdddddddc..c6fffc.......................................
.......................................c..6c..cddddbfcbdbffdddddbbc..bbbdb..c7cccc..bdbbb..cbbdddddffcdbcfbddddc..c6fffc.......................................
.......................................c..6c..cddddbffddbffdddddbbc..bbbdb..cccccc..bdbbb..cbbdddddffbddffcddddc..c6fffc.......................................
....................................c..ccc6c..cddbcbcbddbffdddddbbc..bbbdb..c7cccc..bbbbb..cbbdddddffbddbcbcbddc..c6ccc..c.....................................
....................................c..c6c6c..cddcfcddddbffdddddbbc..bbbdb..c77ccc..bbbbb..cbbdddddffbddddcffddc..c666c..c.....................................
....................................c..c766c..cddcfbddddbffdddddbbc..cbbbb..cccccc..bbbcc..cbbdddddffbddddbfcddc..c666c..c.....................................
....................................c..cc66c.....bddddddbffdddddbbc.........cccccc.........cbbdddddffbdddddddc....c666c..c.....................................
....................................c..cc66c.....dddddddbffdddddbbc.........c7cccc.........cbbdddddffbddddddd.....c666c..c.....................................
....................................c..cc66c..cbbdddddddbffdddddbbc..ccccc..ccc6cc..ccccc..cbbdddddffbdddddddbbc..c66cc..c.....................................
....................................c..cc66c..cdddddddddbffdddddbbc..bbbdb..c666cc..bbbbb..cbbdddddffbdddddddddc..c66cc..c.....................................
....................................c..cc66c..cdddddddddbffbddddbbc..cbbbb..cccccc..bbbbc..cbbdddddffbdddddddddc..c66cc..c.....................................
....................................c..cc66c..cdddddddddbffbbbbbc.............................bbbbbffbdddddddddc..c66cc..c.....................................
....................................c..cc66c..cdddddddddbffbbbbb..............................bbbbbffbdddddddddc..c66cc..c.....................................
....................................c..cc66c..cdddddddbbcffcccccc............................ccccccffcbbdddddddc..c66cc..c.....................................
....................................c..cc66c..cdddddddbbcfffffffd...b....................b...dfffffffcbbdddddddc..c66cc..c.....................................
....................................c..cc66c..cdddddddbbcffffffcd...bc..................cb...dcffffffcbbdddddddc..c66cc..c.....................................
....................................c..cc66c..cddddbbbc.cccccccc1...1cceee44445554444eecbb...bccbbbbcc..bbbddddc..c66cc..c.....................................
....................................c..cc66c..cddddbbb.................e44444555544424e.................bbbddddc..c66cc..c.....................................
....................................c..cc66c..cddbbbccc.c..............e24444455544444e..............c.cccbbbddc..c66cc..c.....................................
....................................c..cc66c..cddbbcffd................e24444445544444e................dffcbbddc..c66cc..c.....................................
....................................c..cc66c..cddbbcffd................e44444445544444e................dcfcbbddc..c66cc..c.....................................
....................................c..cc66c..cbbffccc1................b4344455444444bb................bcccffbbc..c66cc..c.....................................
....................................c..cc66c..cbbffc.....................d44455444443.....................cffbbc..c66cc..c.....................................
....................................c..cc66c...ccccc.....................d44444444443.....................ccccc...c66cc..c.....................................
....................................c..cc66c.....d.......................d42444444443.......................d.....c66cc..c.....................................
....................................c..cc66c.....d.......................d444444444bd.......................d.....c66cc..c.....................................
....................................c..cc66c..ccc1.......................1b4e4422ebb1........................ccc..c66cc..c.....................................
....................................c..cc6cc..c.............................ee222e.............................c..cc6cc..c.....................................
....................................c..cccffccb.............................e44444.............................cccffc6c..c.....................................
....................................c..c7cffd....................................................................dffccc..c.....................................
....................................c..cccffd....................................................................dffcccc.c.....................................
....................................6ccc.ccc1.....................................................................cccffccb.....................................
.........................................c..........................................................................cffc.......................................
.......................................ccb..........................................................................bccb.......................................
...............................................................................................................................................................
...............................................................................................................................................................
...............................................................................................................................................................
...............................................................................................................................................................
...............................................................................................................................................................
...............................................................................................................................................................
...............................................................................................................................................................
...............................................................................................................................................................
...............................................................................................................................................................
...............................................................................................................................................................
...............................................................................................................................................................
...............................................................................................................................................................
...............................................................................................................................................................
...............................................................................................................................................................
...............................................................................................................................................................
...............................................................................................................................................................
...............................................................................................................................................................
...............................................................................................................................................................
...............................................................................................................................................................
...............................................................................................................................................................
...............................................................................................................................................................
...............................................................................................................................................................
...............................................................................................................................................................
...............................................................................................................................................................
...............................................................................................................................................................
...............................................................................................................................................................
...............................................................................................................................................................
...............................................................................................................................................................
...............................................................................................................................................................
...............................................................................................................................................................
...............................................................................................................................................................
...............................................................................................................................................................
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
